const now = Math.floor(Date.now() / 1000);
const day = 86400;

const jds = [
  { JD_ID: 'JD_1001', Date: String(now - 2 * day), Posted_By: 'Alice HR', JD_Text: 'We are looking for a Senior React Developer with 5+ years of experience building complex SPAs. Must have strong TypeScript skills, experience with state management (Redux/Zustand), and a track record of shipping production-grade applications.\n\nResponsibilities:\n- Build and maintain frontend features\n- Collaborate with design and backend teams\n- Review code and mentor junior developers\n\nRequirements:\n- 5+ years React\n- TypeScript proficiency\n- REST & GraphQL APIs\n- Git workflow', Status: 'open' },
  { JD_ID: 'JD_1002', Date: String(now - 5 * day), Posted_By: 'Bob Recruiter', JD_Text: 'Seeking a Node.js Backend Engineer to join our growing platform team. You will design and implement RESTful APIs, manage PostgreSQL databases, and ensure high availability.\n\nMust have:\n- 3+ years Node.js / Express\n- PostgreSQL or MySQL\n- Docker & Kubernetes basics\n- Strong problem solving skills', Status: 'open' },
  { JD_ID: 'JD_1003', Date: String(now - 10 * day), Posted_By: 'Alice HR', JD_Text: 'Product Designer needed to craft beautiful, user-centred experiences across web and mobile. You will own end-to-end design from discovery to handoff.\n\nSkills required:\n- Figma expert\n- User research & usability testing\n- Design systems thinking\n- 3+ years experience', Status: 'closed' },
  { JD_ID: 'JD_1004', Date: String(now - 15 * day), Posted_By: 'Carol Manager', JD_Text: 'DevOps Engineer to manage our CI/CD pipelines, infrastructure as code, and cloud operations on AWS.\n\nMust have:\n- AWS (EC2, ECS, RDS, S3)\n- Terraform or Pulumi\n- GitHub Actions / Jenkins\n- On-call readiness', Status: 'open' },
  { JD_ID: 'JD_1005', Date: String(now - 20 * day), Posted_By: 'Bob Recruiter', JD_Text: 'Data Analyst to turn raw data into actionable business insights. Work closely with product and finance teams.\n\nRequirements:\n- SQL (advanced)\n- Python (pandas, matplotlib)\n- Tableau or Looker\n- Strong communication skills', Status: 'open' },
];

const applicants = [
  { Applicant_ID: 'APP_2001', JD_ID: 'JD_1001', Date: String(now - 1 * day), Sender: 'james_dev', Message: 'Hi, I have 7 years of React experience and have led frontend teams at two startups. Proficient in TypeScript, Redux Toolkit, and React Query. Happy to share my portfolio.', Result: 'STRONG', Reason: 'Exceeds all React and TypeScript requirements. Team lead experience is a bonus.', Phone: '+1 415 555 0101', Email: 'james.wilson@email.com', Name: 'James Wilson' },
  { Applicant_ID: 'APP_2002', JD_ID: 'JD_1001', Date: String(now - 1 * day), Sender: 'sarah.chen', Message: 'I am a frontend developer with 3 years of React. Still learning TypeScript but comfortable with JavaScript ES6+. Looking to grow.', Result: 'PARTIAL', Reason: 'Meets React requirement but TypeScript is a gap. Could work with mentorship.', Phone: '+1 212 555 0182', Email: 'sarah.chen@email.com', Name: 'Sarah Chen' },
  { Applicant_ID: 'APP_2003', JD_ID: 'JD_1001', Date: String(now - 2 * day), Sender: 'mike_design', Message: 'I am a designer who knows some React. Can build simple components. Interested in the role.', Result: 'WEAK', Reason: 'Primarily a designer. React experience is superficial and TypeScript is missing.', Phone: '+234 801 555 0143', Email: 'mike.okafor@email.com', Name: 'Mike Okafor' },
  { Applicant_ID: 'APP_2004', JD_ID: 'JD_1002', Date: String(now - 3 * day), Sender: 'priya_s', Message: 'Backend engineer with 5 years of Node.js. Built microservices on AWS with PostgreSQL, Redis, and Docker. AWS certified.', Result: 'STRONG', Reason: 'Strong match on all backend requirements. AWS certification is a plus.', Phone: '+91 98765 43210', Email: 'priya.sharma@email.com', Name: 'Priya Sharma' },
  { Applicant_ID: 'APP_2005', JD_ID: 'JD_1002', Date: String(now - 4 * day), Sender: 'tombradley', Message: 'PHP developer looking to transition to Node.js. Have done some Express tutorials and built a side project API.', Result: 'WEAK', Reason: 'Limited production Node.js experience. Transition risk for a senior role.', Phone: '+44 20 7946 0501', Email: 'tom.bradley@email.com', Name: 'Tom Bradley' },
  { Applicant_ID: 'APP_2006', JD_ID: 'JD_1003', Date: String(now - 6 * day), Sender: 'emma.n', Message: 'Product designer with 6 years experience at fintech companies. Expert in Figma, ran user research sessions, and built and maintained two design systems.', Result: 'STRONG', Reason: 'Perfect match. Fintech background adds relevant domain experience.', Phone: '+84 90 555 0167', Email: 'emma.nguyen@email.com', Name: 'Emma Nguyen' },
  { Applicant_ID: 'APP_2007', JD_ID: 'JD_1004', Date: String(now - 8 * day), Sender: 'raj_devops', Message: 'DevOps engineer 4 years, AWS Solutions Architect certified. Built CI/CD with GitHub Actions, manage Terraform infrastructure for 3 production environments.', Result: 'STRONG', Reason: 'Excellent fit across all requirements. Certifications confirm expertise.', Phone: '+91 91234 56789', Email: 'raj.patel@email.com', Name: 'Raj Patel' },
  { Applicant_ID: 'APP_2008', JD_ID: 'JD_1004', Date: String(now - 9 * day), Sender: 'lucypark', Message: 'Junior sysadmin interested in DevOps. Familiar with Linux and basic Docker usage. No cloud experience yet.', Result: 'NONE', Reason: 'Too junior. Missing cloud and IaC requirements entirely.', Phone: '+82 10 5555 0128', Email: 'lucy.park@email.com', Name: 'Lucy Park' },
  { Applicant_ID: 'APP_2009', JD_ID: 'JD_1005', Date: String(now - 12 * day), Sender: 'david_m', Message: 'Data analyst 3 years. SQL expert, Python with pandas daily, built 10+ Tableau dashboards for executive reporting. Looking for new challenges.', Result: 'STRONG', Reason: 'Solid match on all technical and communication requirements.', Phone: '+233 24 555 0199', Email: 'david.mensah@email.com', Name: 'David Mensah' },
  { Applicant_ID: 'APP_2010', JD_ID: 'NONE', Date: String(now - 14 * day), Sender: 'anna_k', Message: 'Interested in any open positions at your company. I am a generalist with marketing and some data background.', Result: 'UNKNOWN', Reason: 'No specific JD matched. Generalist profile.', Phone: '+48 500 555 0110', Email: 'anna.kowalski@email.com', Name: 'Anna Kowalski' },
];

module.exports = { jds, applicants };
